set(STM43CUBEF4_DIR ${BOARD_DIR}/STM32CubeF4)
set(CMSIS_DIR ${STM43CUBEF4_DIR}/Drivers/CMSIS)
set(CMSIS_INCLUDE_DIRECTORIES
    ${CMSIS_DIR}/Include
    ${CMSIS_DIR}/Device/ST/STM32F4xx/Include
)
set(CMSIS_TEMPLATES_DIR ${CMSIS_DIR}/Device/ST/STM32F4xx/Source/Templates)
set(HAL_DIR ${STM43CUBEF4_DIR}/Drivers/STM32F4xx_HAL_Driver)
set(HAL_INCLUDE_DIRECTORIES ${HAL_DIR}/Inc)
set(HAL_SRC_DIR ${HAL_DIR}/Src)
set(USBDEVLIB_DIR ${STM43CUBEF4_DIR}/Middlewares/ST/STM32_USB_Device_Library)
set(USBDEVLIB_INCLUDE_DIRECTORIES
    ${USBDEVLIB_DIR}/Core/Inc
    ${USBDEVLIB_DIR}/Class/CDC/Inc
)
set(USBDEVLIB_SRC_DIR ${USBDEVLIB_DIR}/Core/Src)
set(USBDEVLIB_CDC_SRC_DIR ${USBDEVLIB_DIR}/Class/CDC/Src)
